puppetlabs/puppetlabs-powershell

README.md
=> Edits to grammar, markdown, and format to match current styleguide.

.sync.yml, Gemfile
Beaker-rspec is used by acceptance testing and should be present for acceptance
testing to properly pass.
=> (MODULES-2207) Add Beaker-Rspec

.sync.yml, Gemfile
Ensure that beaker rspec is at least on a version that supports the
use of specinfra and is not known to contain bugs.
=> (MODULES-2207) bin beaker-rspec to ~> 5.1

Gemfile
For Puppet older than 3.5.0 on Windows, a facter version at or under
1.7.5 should be selected for greatest compatibility when requesting
a gem puppet version and if a facter version has not been specified.
=> (MODULES-2443) Ensure Facter version for old Puppets

Gemfile
Update the Beaker version to use "2.20" which has an important fix for PE
installations.
=> (MODULES-2452) Update Beaker Version

Gemfile
We don't use DevKit in CI, so it should not be required for
normal testing purposes.
=> (maint) update modsync / fix build

appveyor.yml
Running gem install bundler on appveyor is redundant because it is already present.
Removing it will speed up build times
=> (FM-4881) Remove gem install bundler on Appveyor

Gemfile
- Rake 11 was recently released with an incompatible change for
versions of rspec-core < 3.4.4 (released / fixed 3/9/2016). The
current Gemfile pessimistically versions against rspec 3.0.0, but
that prevents it from installing a newer version that would require
the appropriate / compatible version of rspec-core.  Without this
change rspec-core 3.0.4 gets installed, which prevents rake from
running.
Without the change, any fresh bundles across various OSes, including
CI in TravisCI and AppVeyor will fail to run any rake tasks.
An alternate solution would limit rake to < 11, but in testing this
seemed just as valid.
=> (maint) Changed allowed rspec version

.sync.yml, appveyor.yml, lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell_manager.rb, lib/puppet_x/templates/invoke_ps_command.erb, metadata.json, spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb
Supercedes #74 
Channeling @jpogran from previous PR:
> This PR is a port of the PowerShell session code from the DSC module. This code includes some significant speed and system utilization improvements.
> 
> In the prior version every call to exec started a brand new PowerShell process for each of the exec modes: command, onlyif and unless. This was costly in both time and system resources as PowerShell takes significant time to intialize and frequent process creations spike cpu on the target system.
> 
> In this version, a single PowerShell process is created that lives not only for all the modes of exec, but also for the entirety of the Puppet run. We still have a one time cost of time and system utilization for
> process creation for the entire run, but gain the ability to run …
=> (MODULES-2962) Reuse PowerShell Session

lib/puppet_x/puppetlabs/powershell_manager.rb
- In a4cd1f5ff85f4b05b20b4325d98618ce7df2d0a4, an effort was made
to ensure that the code in PowerShellManager that consumed FFI was
written in a Puppet version agnostic way.
Unfortunately, one small item was missed in the way that FFI
functions are declared.  Rewrite the code to not require the
api_types.rb helper attach_function_private from Puppet 3.7+
=> (maint) Fix private FFI declarations

Gemfile, spec/spec_helper.rb
Beaker needs a version of Rake less than
11 due to using `last_comment' in
rake_task.rb:62. Reduce the version of Rake
down to the same dependency that Beaker does
as a development dependency.
Paired with Glenn Sarti <glenn.sarti at puppetlabs dot com>
=> (FM-4952) Restrict Rake to ~> 10.1

spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Due to the changes from MODULES-2962, ticket MODULES-2634 is fixed
as a side effect. Besides the module itself using try/catch semantics
in a templated PS1 file, it supports any kind of syntax or formatting..
This commit adds two tests to ensure that this is the case. One for
integration testing, the other for acceptance.
=> (MODULES-2634) Test try/catch in PowerShell provider

lib/puppet_x/templates/invoke_ps_command.erb
When the function to reset the Environment Variables for the single
session PowerShell process was added, the Verbose paramater was mistakenly
left on the Remove-Item and Set-Item cmdlets. This causes a Verbose
message to be written every time the provider is executed, polluting the
Puppet Debug stream. This is only an issue when MODULES-3137 is
implemented as it enables logging Verbose statements.
This removes the Verbose parameters.
=> (MODULES-3280) Remove Verbose Environment Variable Handling

spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
This commit reverts the changes introduced in PR #84 (6ed1d95). These tests
failed in CI and prevented further testing.  This PR will probably be
superceded by MODULES-3285 in the future.
=> Revert "(MODULES-2634) Test try/catch in PowerShell provider"

README.md
Prior to this, the README had examples of containing multi-line or
complex PowerShell scripts to be `exec`'d as templates. The examples
shown weren't actually templates and didn't have any ERB code in them.
This led to some confusion on first glance because the PowerShell code
shown didn't have any dynamic code in it; it was static code. It also
could lead some users to believe that the template() function is required.
This commit fixes that by converting the examples shown to using the
file() function and static files. It also leaves a note that actual
templates can be used if the PowerShell scripts do in fact need to be
dynamic or access Puppet variables.
Fixes https://tickets.puppetlabs.com/browse/MODULES-3192
=> (MODULES-3192) Use file() instead of template() in the README

.sync.yml, NOTICE
The previous commit (PR #93) ommited the original author, Josh Cooper, from
the copyright information. This commit adds Josh as the original author and
includes the updates from a modulesync.
=> (maint) Update copyright notice with correct authors

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/templates/invoke_ps_command.erb
- Use the CoreCLR compatible `WaitHandle.WaitOne(timeout)`
- Don't invoke `powershell.exe` with `-Sta`
=> (MODULES-3344) Nano Server Compatibility

lib/puppet_x/templates/invoke_ps_command.erb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
When we switched to a single PowerShell sessions using PowerShell
Runspaces, we lost the information from the Error, Debug, and Verbose
streams. By implementing a custom PowerShell Host, and the
PSHostUserInterface and PSHostRawUserInterface interfaces we capture
any information written to those streams
=> (MODULES-3137) Log PowerShell Streams

spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Due to the changes from MODULES-2962, ticket MODULES-2634 is fixed
as a side effect. Besides the module itself using try/catch semantics
in a templated PS1 file, it supports any kind of syntax or formatting.
This commit adds a unit test and an acceptance test to ensure that this
is the case.
=> (MODULES-2634) Verify try/catch with PowerShell module

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb
- DSC and PowerShell both used the path of
lib/puppet_x/puppetlabs/powershell_manager.b for their uniquely
namespaced PowerShellManager class.
Unfortunately, while the file was namespaced differently, upon
extraction, the files would collide / overwrite one another, so
only the last file extracted would win.
=> (FM-5240) Prevent powershell_manager DSC conflict

CHANGELOG.md, metadata.json
This commit prepares the module for release version 2.0.1.  This commit
also adds Windows 10 as a supported platform for the module as it was
omitted in error in the last release.
=> (FM-5241) Release Powershell 2.0.1

CHANGELOG.md
The release dates for v2.0.0 and v2.0.1 had the incorrect date.  This
commit ammends the release date
=> (maint) Fix changelog release dates

lib/puppet/provider/exec/powershell.rb
- Because this module can be run on Puppet 3.8, which can run on
the system Ruby of a Linux machine (such as CentOS 6), it's
possible that the cdoe will be parsed in a Ruby 1.8.7 environment.
Move to require with a manually constructed path, which is the
effectively the same thing as require_relative in newer Rubies.
=> (maint) Remove require_relative for Ruby 1.8.7

spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/spec_helper_acceptance.rb
```
Finished in 4 minutes 31.7 seconds (files took 2 minutes 24.6 seconds to load)
27 examples, 0 failures
```
=> (MODULES-2634) Try / Catch Test Updates

.gitignore
A binary test file was committed in error in MODULES-2634.  This commit removes the test file and updates gitignore so that test files in that location (tmp/...) will be ignored in future
=> (MODULES-2634) Remove unnecessary binary test file

lib/puppet/provider/exec/powershell.rb
In this module, if a user using puppet 3.X  uses a try/catch
statement without a newline at the end it will either be entirely
ignored or it will fail. This is an artifact of how we are using
powershell in older puppet versions, i.e. through a file redirection
into the Command parameter to powershell.exe.
If we add a newline to the end of the tempfile that is passed to PS,
we can execute any logic construct in PS. This fix uses `puts` instead
of `write`, which automatically adds a newline to the end of the script
content.
=> (MODULES-2634) Fix PS try/catch in puppet 3.X

lib/puppet/provider/exec/powershell.rb
Previously, the PowerShell module was not correctly executing
code inside of try / catch blocks in a templated script on Windows
2008 R2 x64, PE version 3.2.3.
This commit appends a newline to the manifest, since
PowerShell needs multiple lines to correctly parse it.
=> (MODULES-2634) PowerShell Module doesn't run template with try/catch

README.md
This commit
- Adds the minimum powershell version to the Limitations section
- Removes Window 2003 as a supported OS for this module
- Adds a space in the markdown headers between the hash and text.  While this
renders correctly in GitHub and the Puppet Forge some editors and parsers
require a white space.
[ci skip]
=> (MODULES-3468) Update README.md

spec/unit/provider/exec/powershell_spec.rb
- Some internal changes to transaction behavior that are part of
Puppet 4.6, have induced a new problem with the existing tests that
invoked the compiler.  Transactionstore.yaml files are now
produced when a transaction is processed, for the sake of
identifying changes as part of the `corrective changes` feature.
Without the Puppet[:statedir] explicitly set, compiling a catalog
and executing a transaction will attempt to write a YAML file to
c:\dev\null.
Instead, explicitly set the path to allow for a real file to be
written as part of the transaction.
=> (maint) Fix test failures for Puppet 4.6

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1.erb, spec/acceptance/exec_powershell_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb
Previously, the a timeout value could be specified in a resource however that
value was ignore and the default of 300s was used by the powershell manager.
This commit passes throught the timeout value from the resource into the
powershell manager and also adds an acceptance test to verify this behaviour.
This builds in PR #125
=> (MODULES-3709) Respect resource timeout interval in powershell manager

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1.erb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb
Previously  the cwd resource parameter was not being used during powershell
script execution.  This PR checks to see if the cwd parameter is specified
on the resource and if so, inserts a 'Set-Location' command at the very top of
the powershell script to change the working directory prior to script execution.
The working directory will always default to the current directory of the process
which creates the powershell manager.  The working directory is not modified
across runspaces/
This PR also moved the default execution timeout value to a separate class
function so that the execute function can be invoked correctly i.e. If the
execute method is to be called with a custom working directory, but with a default
timeout.
=> (MODULES-3565) Change the working directory if specified in the resource 

lib/puppet_x/templates/init_ps.ps1.erb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Previously any error in a user supplied code block would error with `Exception
calling "EndInvoke" with "1" argument(s): ....` however this is not very useful
and hides required debugging information for users.  This commit:
- Emits the inner exception on user exit code if it exists.  The inner exception
is what caused the EndInvoke to fail an contains the true reason why an error
was thrown
- Modifies the error string output to emit the `ErrorRecord.InvocationInfo`
which contains the line number and offset where the error occure and an
excerpt of the offending line
- Adds tests to expect correct messages for simple errors
=> (MODULES-3443) Emit better user code exceptions

README.md
The behavior about $LASTEXITCODE was modified in MODULES-3399 however there
was no documentation to demonstrate the change.  This PR modifies the README
with the new behavior and example code.
[ci skip]
=> (MODULES-3588) Update documentation for change in MODULES-3399

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- Existing test verified that 64k generated within PowerShell could
be sent back to Ruby without deadlocking the Ruby parent process.
Add a new test that originates 64k+ on the Ruby side and ensures
that the data is properly round-tripped back to Ruby after
passing it over stdin to PowerShell (which is implemented under
the hood with popen3 via a named pipe).
- Previously it was possible to call exit against PowerShellManager
and not have it completely terminate due to attempting to write to
broken pipes, etc.
Now verify state prior to attempting to close since Ruby will raise
an IOError if calling close against an already closed IO instance
Also ignore any errors raised when trying to 'exit' the instance
- Instead of having write_sdin / drain_pipe contain their own
exception handlers, …
=> (MODULES-3875) Improve PowerShellManager resilience to failure

spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/spec_helper.rb
Previously the integration tests for testing error behavior were passing on
Powershell 3+ however the error parsing is different in Powershell 2.0. This
commit modifies the test expectations for a line and char to returned but the
content of the line and char values are ignored.  This means the tests will now
pass on all Powershell versions but still ensure the correct behavior.
Currently the integration tests are failing on PowerShell version 2.0 or less.
This commit adds a helper function to determine the Powershell version without
the Powershell Manager code, and then skips the PowerShell Manager integration
tests if the PowerShell version is 2.0 or less.
Previously the working directory tests would fail if the path differed with casing however under
Windows paths are not case …
=> (MODULES-3443) Modify error test for differences in Powershell version

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb
- The code as implemented was subtly flawed.  When draining pipes in
separate threads, reads proceed until PS has signaled that it has
executed code and written output.
Code existed to drain the pipe in case that race occurred. However,
the code only performed a single read with the Ruby IO.gets method,
which reads until the next newline character.
The console width is defined as 120 characters, so a block of XML
written as a result could end up split up / incomplete.
- Instead, the code should have been reading while the pipe was
considered readable, ensuring that it reads all remaining data
after receiving a completion signal.
- This bug was trivially reproducible on Windows 2008R2 + PS2, but
not PS5.  With the fix in place, the problem no longer occurs.
=> (MODULES-3144) Fix race condition draining pipes

spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/spec_helper.rb
- In 5072e28 changes were made to exclude PowerShell 2 from running
integration specs against PowerShellManager.  There are currently
only 2 failures related to exceeding the Console BufferSize and
how PowerShell 2 sends the output through PuppetPSHostUserInterface
that actually need to be marked pending.
Re-enable the 47 skipped tests under PowerShell 2 and mark the
other 2 failing tests as pending.
=> (maint) Re-enable PowerShell 2 tests

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb
- Previous code made two bad assumption that could result in the
module crashing when anything is written to the stderr stream via
native executables.
The first assumption is that there is a non-nil value passed back in
the XML response `stderr` element.  It's completely valid to have no
pre-existing value present.
The second assumption was that the captured stderr was a bare string.
It will never be a bare string and should always be a single element
string array at the very least.
- Adjust the code to handle these situations accordingly and introduce
a new test that creates multiline stderr output.
=> (maint) Fix multiline stderr capture

CHANGELOG.md, metadata.json
Changelog updated with all changes since 2.0.2 release
=> (maint) Update changelog and metadata for release

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- Instead of using the stdin present by popen3, create a separate
NamedPipe listener directly inside the PowerShell code.  This can
be written to from Ruby by calling File.Open with a Windows style
.\\.\pipe\ path to the pipe.  This File is a Ruby IO instance that
behaves just like the existing streams returned by popen3.
Send commands through this mechanism for several reasons:
- Guarantee the protocol between Ruby client and PowerShell host,
so that any normal PowerShell stdin processing problems are
averted.  WMF 5.1 (Windows 10 anniversary update / Windows Server
2016) accidentally made some breaking changes to the stdin
parsing which causes existing code to completely fail.  This new
implementation works around that problem completely.
- Strictly control the encoding so that passing …
=> (MODULES-3690) Use custom binary pipe IPC

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/compatible_powershell_version.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/puppetlabs/powershell/powershell_version.rb, spec/unit/puppet_x/puppetlabs/powershell/compatible_powershell_version_spec.rb, spec/unit/puppet_x/puppetlabs/powershell/powershell_version_spec.rb
Determine if the PowerShell version installed is compatible with module. When folks are using PowerShell 3+, they are on .NET Framework 4+, so they are completely compatible with the PowerShell Manager. When folks are using PowerShell v2 and .NET 3.5, they are also compatible, as `System.IO.Pipes` requires at least .NET Framework 3.5.
However if they are running PowerShell v2 with .NET 2.0 (which is not going to happen very often, but it represents a base install on Windows Server 2008 and R2), it is not compatible with the PowerShell Manager. Ensure it switches back to v1 functionality.
Note:
This brings the ability to detect the PowerShell version over from the PowerShell DSC module. I adjusted it to use `PuppetX::PuppetLabs::PowerShell::PowerShellVersion` instead of just …
=> (MODULES-3690) PowerShell v2 + .NET Framework less than 3.5 is unsupported for PowerShell Manager

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1
- In the finally block of the Start-PipeServer listener, explicitly
Dispose of the current loaded PowerShell runspace.
=> (MODULES-4754) Dispose runspace on pipe close

lib/puppet/provider/exec/powershell.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Previously the PowerShell 2.x provider did not use the environment parameter
from the exec Puppet Type.  This commit updates the PowerShell manager to
include custom environment variables passed from the Puppet Resource and
integration tests for this behaviour.
=> (MODULES-4138) Provider will respect the environment parameter

CHANGELOG.md
This commit fixes the typo in the date of the 2.1.1 release.
=> (maint) Update date in Changelog

lib/puppet/provider/exec/powershell.rb
This commit renames the global POWERSHELL_UPGRADE_MSG to
POWERSHELL_MODULE_UPGRADE_MSG to avoid variable name conflicts
with other modules installed, namely DSC.
This relates to PR https://github.com/puppetlabs/puppetlabs-dsc/pull/304
=> (MODULES-5224) Fix Global Warning variable

lib/puppet/provider/exec/powershell.rb, spec/unit/provider/exec/powershell_spec.rb
This commit renames the PowerShell binary name from PowerShell to
pwsh. This is because the name of the binary has changed in the
latest PowerShell betas.
=> (MODULES-6081) Rename PowerShell executable

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb
Prior to this commit, the timeout waiting for PowerShell to start
was only 10 seconds; this was not, in practice, a long enough
period of time for multiple customers, especially when a node is
under heavy load. This commit increases the timeout to 30 seconds.
=> (MODULES-4748) Increase timeout for opening PowerShell

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Prior to this commit if a timeout occurs while waiting for the
connection to a named pipe then a zombie process is left on the
system as the code to close or kill it is never called. This commit
ensures that such zombie processes are removed before the error is
raised.
=> (MODULES-4748) Prevent zombie procs from timeout

lib/puppet_x/templates/powershell/init_ps.ps1
The newest image for Windows 2008r2 is exhibiting different behavior
for loading .NET assemblies than we have seen in the past. The
System.Core assembly is not loaded into the PowerShell host process by
default any longer. This causes the init.ps1 script in the module to
to fail to start a Pipe Server to receive PowerShell scripts to be
executed. This change always attempts to load the System.Core
assembly prior to creating the pipe server object. Explicity loading the
assembly fixes the issue and the newest image becomes usable again. This
fix is also require to fix any moduels that depend on the PowerShell
exec provider working properly.
=> (IMAGES-795) 2008r2 template failing PowerShell module tests

lib/puppet_x/templates/powershell/init_ps.ps1
The newest image for Windows 2008r2 is exhibiting different behavior
for loading .NET assemblies than we have seen in the past. The
System.Core assembly is not loaded into the PowerShell host process by
default any longer. This causes the init.ps1 script in the module to
to fail to start a Pipe Server to receive PowerShell scripts to be
executed. This change always attempts to load the System.Core
assembly prior to creating the pipe server object. Explicity loading the
assembly fixes the issue and the newest image becomes usable again. This
fix is also require to fix any moduels that depend on the PowerShell
exec provider working properly.
=> (MODULES-6927) Fix Pipe Server on Win 2008r2

README.md
- It's unnecessary to use PowerShell sub-expressions in the
examples given. Remove superfluous syntax to prevent user confusion
=> (maint) Minor PowerShell syntax updates to README

spec/acceptance/exec_powershell_spec.rb
This commit removes an errant pry command that was commented out.
=> (maint) Remove errant pry command

README.md, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Some other Puppet Exec providers will treat a `timeout` value of `0` as
an infinite timeout. We have chosen not to support an infinite timeout
in this provider, so this change will ensure that a sensible value is
used if the user passes in `0` as the timeout. It also fixes the README
documentation to make it clearer that `0` is not supported, and that
attempting to use it will result in the default timeout of 300 seconds
being used instead.
=> (MODULES-7018) Fix Zero Timeout Behavior

.sync.yml, Gemfile
First step to getting converted over to use PDK is to make sure that your tests pass with the latest version of rspec-puppet.
=> (PDK-1035) Remove the rspec-puppet pin

lib/puppet/provider/exec/pwsh.rb, spec/acceptance/exec_pwsh_spec.rb, spec/spec_helper_acceptance.rb, spec/unit/provider/exec/pwsh_spec.rb
PowerShell 6 now uses a different binary and has different installation locations
compared to Windows PowerShell.  This commit adds a new provider called pwsh
which will execute scripts but using PowerShell 6 (pwsh).  Later commits will add
advanced features, but this commit adds a basic provider with tests that works
only on Windows, with PowerShell 6 in the default installation location.
=> (MODULES-8355) Add pwsh provider

lib/puppet/provider/exec/pwsh.rb, spec/acceptance/exec_pwsh_spec.rb, spec/acceptance/files/command-to-outfile.ps1, spec/acceptance/files/get-command-win.ps1, spec/spec_helper_acceptance.rb, spec/unit/provider/exec/pwsh_spec.rb
Previously the pwsh provider only functioned on Windows operating systems.
This commit;
* Modifies the provider to not be confined to Windows operating systems
* Modifies the spec tests to be able to run on non-Windows platforms
* Modifies the acceptance tests to be able to run on non-Windows platforms
=> (MODULES-8357) Add cross platform support for pwsh provider

spec/spec_helper_acceptance.rb
Previously the powershell module was only being installed onto the
default host.  However this meant the module was only being installed
onto the agent, not the server, which then caused issues during tests
because the module content was not 'file syncd' from the master and
tests were failing as it couldn't find the powershell provider.
This commit uses the module install helper from beaker to install on
all hosts.
=> (maint) Fix module installing in master-agent scenario

README.md, lib/puppet/provider/exec/pwsh.rb, metadata.json, spec/integration/provider/exec/pwsh_spec.rb, spec/unit/provider/exec/powershell_spec.rb, spec/unit/provider/exec/pwsh_spec.rb
~~Builds on PR #245~~
---
Previously the pwsh provider only looked in the system path and some
predefined paths on Windows.  However PowerShell Core can be installed
anywhere as it is now a tarball/zipfile installation.  This means a
user should be able to arbitrarily define a location for the provider
to use.
This commit removes the :pwsh command because command resolution
can not use a custom path when searching. This is normally used to see
if a provider is applicable.  It is then replaced by a method called
get_pwsh_command which uses a copy of the Puppet `which` command which
can use custom search paths when locating binaries.
Note we can not extend or update the Puppet version of this code as
the which method is private. In this case we copy the code verbatim
and then modify it. …
=> (MODULES-8356) Search for pwsh binary

lib/puppet/provider/exec/pwsh.rb, spec/unit/provider/exec/pwsh_spec.rb
Previously the pwsh provider was modified to search for the pwsh binary
in a user specified path.  However this introduces a lot of new code.
This commit removes the redundant code and uses a public method within
Puppet (.withenv) to actually do the searching
This commit also uses a simple memoizing pattern to remember the path
to avoid costly IO when searching.  This commit also adds tests for
this scenario.
=> (MODULES-8356) Improve pwsh searching

lib/puppet/provider/exec/powershell.rb, lib/puppet/provider/exec/pwsh.rb, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, spec/acceptance/exec_pwsh_spec.rb, spec/integration/provider/exec/pwsh_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/spec_helper_acceptance.rb, spec/unit/provider/exec/powershell_spec.rb, spec/unit/provider/exec/pwsh_spec.rb
In preparation to add cross platform support to the PowerShell Manager,
this commit refactors the common execution code in the powershell provider into
the PuppetX::PowerShell::PowerShellManager.execute_resource method.  This
takes PowerShell code and a puppet exec resource and executes this using the
PowerShell Manager.
Previously the powershell command was a string which also contain the powershell
invocation commands.  This commit also separates the powershell command and arguments
so that we can call pwsh or powershell separately from the same PowerShell Manager.
---
Previously the pwsh provider would save a file to a temporary location and then
execute that. This is considered a legacy method.  The more modern method, which
is used in the Windows PowerShell provider, is to use the …
=> (MODULES-8358) Add PowerShell manager to pwsh provider

spec/spec_helper_acceptance.rb
Previously the spec_helper_acceptance was updated to install PowerShell core
of EL based operating systems e.g. CentOS 7, however the installation
instruction was accidentally copied from the ubuntu instructions which tried
to use Apt instead of Yum.  This commit fixes the typo error.
=> (MODULES-8358) Fix typo for EL based test hosts

lib/puppet/provider/exec/powershell.rb, spec/acceptance/exec_powershell_spec.rb, spec/unit/provider/exec/powershell_spec.rb
Previously in MODULES-3495 cross platform support was added to the powershell
provider.  However as part of MODULES-8358 the pwsh provder was added to
achieve the same.  This means that the non-Windows platform support within the
powershell provider can be removed as it is no longer necessary.  Also note that
as this was marked as experimental, and had known issues with functioning
therefore the removal will not require a major version bump of the module.
This commit removes the support and also modifies the unit and acceptance tests
to not test the powershell provider on non-Windows platforms.
=> (MODULES-8359) Remove non-Windows support for powershell provider

.travis.yml
This commit updates our travis config to use xenial, 16.04 instead of trusty, 14.04, because trusty has reached EOL and is now causing errors.
=> (MAINT) Update linux distro in travis

CHANGELOG.md, lib/puppet_x/puppetlabs/powershell/powershell_manager.rb
This commit increases the timeout for waiting on the named
pipe to open. This resolves issues where servers under
heavy load do not open the pipe quickly enough.
=> (MODULES-9084) Increase pipe timeout to 180s

metadata.json
The issues link points at an area in Jira that no longer exists. This
change fixes it to point at a more generic place that will allow users
to create a a ticket.
=> (MODULES-9473) Fix Issues Link

.rubocop.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, appveyor.yml, metadata.json, spec/default_facts.yml, spec/spec_helper.rb
This PR was created using this script in stages running `pdk update` and committing individual changes in multiple iterations. Some manual fixes interspersed to reduce aberrations.
```
#! /usr/bin/ruby
require 'yaml'
contents = YAML.load(File.read(".sync.yml"))
contents[".gitlab-ci.yml"] = {'delete' => true}
contents["spec/spec_helper.rb"] ||= {}
contents["spec/spec_helper.rb"]['coverage_report'] = true
gitignore = contents[".gitignore"] ||= {}
gitignore["required"] ||= []
gitignore["required"] -= ["---.project"]
gitignore.delete("required") if gitignore["required"].empty?
contents.delete(".gitignore") if contents[".gitignore"].empty?
contents.delete("spec/default_facts.yml") if contents["spec/default_facts.yml"] == {"unmanaged" => true}
[".travis.yml", "appveyor.yml"].each do |f| …
```
=> (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups

.sync.yml, .travis.yml, metadata.json
This requires a few changes to the pdk-templates from this PR: https://github.com/puppetlabs/pdk-templates/pull/293
=> Start managing CI files

lib/puppet/provider/exec/powershell.rb, lib/puppet/provider/exec/pwsh.rb
This modifies the providers to use a confine statement to a feature found in the dependent pwshlib module, preventing Puppet runs from failing outright if the dependency is not found.
=> (MODULES-10389) - Safeguard powershell provider loading

.sync.yml, .travis.yml, Gemfile, metadata.json
Request for a review
Updated .sync.yaml file to disable forge upload
Then ran pdk update to make changes to the files.
=> (maint) disable forge upload

metadata.json
Prior to this commit the metadata erroneously claimed support for 4x versions of Puppet, on which it has not been tested and would fail to run as the `ruby-pwsh` dependency requires Ruby 2.3 or higher which ships in Puppet 5x.
Further, Puppeet 4x is no longer officially supported at all.
=> Correct supported Puppet lower bound to 5.5.0

lib/puppet/provider/exec/powershell.rb, spec/acceptance/exec_powershell_spec.rb, spec/acceptance/exec_pwsh_spec.rb, spec/spec_helper_acceptance_local.rb, spec/unit/provider/exec/powershell_spec.rb, spec/unit/provider/exec/pwsh_spec.rb
Prior to this commit the PowerShell exec provider used the commands idiom to
load the PowerShell executable path for use. Once the module was refactored
to rely on the ruby-pwsh gem via the puppetlabs/pwshlib module, the code for
determining the path was updated to depend on a helper function. However,
the commands method is (apparently?) evaluated during catalogue compilation,
causing the Puppet run to explode unexpectedly if the dependent module is
not available.
This commit removes the commands idiom and relies on the feature confine which
should evaluate during a Puppet run and, when that feature is not found
(because puppetlabs/pwshlib is not installed) it will report that the provider
is not functional rather than blow up the entire Puppet run.
=> (MODULES-10539) Remove commands idiom from PowerShell provider

.sync.yml, Gemfile
Neither beaker nor puppet-blacksmith is used anymore.
=> Remove system-tests group from Gemfile

spec/acceptance/exec_powershell_spec.rb, spec/acceptance/exec_pwsh_spec.rb, spec/spec_helper_acceptance_local.rb
This was added to Litmus so we can remove it here. Also prevents us having a method that could potentially diverge from the Litmus one.
=> (maint) Remove interpolate_powershell method

.github/pull_request_template.md, .github/workflows/release.yml, CHANGELOG.md, CONTRIBUTING.md, HISTORY.md, metadata.json, spec/fixtures/scripts/install_pwsh/windows.ps1
Removal of any inappropriate or offensive terminology from the codebase.
=> (IAC1001) - Removal of inappropriate terminology

lib/puppet/provider/exec/powershell.rb, lib/puppet/provider/exec/pwsh.rb
Prior to this commit there was no way to modify the pipe_timeout
parameter when instantiating a PowerShell Manager instance, users
were stuck with the default defined in ruby-pwsh (30s). If this
time is insufficient to start the host process, the exec failed
with no way to extend it short of modifying the provider.
This commit updates the definition of the ps_manager by checking
to see if the timeout parameter is specified on the resource and,
if so, inheriting that to re-use for the pipe timeout.
=> (MODULES-10722) Inherit pipe_timeout from timeout

metadata.json, spec/fixtures/scripts/install_pwsh/debian_11.sh
Work previously halted due to Powershell itself not yet fully supporting Debian 11
=> (IAC-1734) - Certify Debian 11

metadata.json, spec/fixtures/scripts/install_pwsh/ubuntu_22.04.sh
(GH-cat-11) Certify Support for Ubuntu 22.04
pdk version: `2.3.0`
=> pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04

metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for Windows Server 2008 & 2008 R2 was removed. 
Support for Windows 7 & 8 was removed.
Support for Fedora 27 & 28 was removed.
Support for OSX 10.12, 10.13 & 10.14 was removed.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
=> (MAINT) Dropped support for Windows(7,8,2008 + 2008 R2(Server), Fedora(27+28) and OSX OS's(10.12-.14)

spec/unit/provider/exec/powershell_spec.rb, spec/unit/provider/exec/pwsh_spec.rb
Prior to this commit, spec tests for pwsh were using old syntax and conventions.
This commit updates the tests so that they match the syntax and conventions being used throughout the rest of our modules.
=> (CONT-133) Update outdated spec tests

.github/workflows/ci.yml, .github/workflows/nightly.yml
Skip CI pipeline for ARM OS due to power-shell package unsupportability. 
```
Last metadata expiration check: 0:01:43 ago on Thu 18 Jan 2024 09:11:38 AM UTC.
Error:
Problem: cannot install the best candidate for the job
- package powershell-7.3.11-1.rh.x86_64 from packages-microsoft-com-prod does not have a compatible architecture
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
=> (CAT-1696) - Skip CI pipeline for ARM OS

hiera.yaml, lib/puppet/provider/exec/powershell.rb
Replaced legacy fact `osfamily` with `os.family`
As a part of making modules 'puppet 8` compatible without deprecation warnings, we are replacing these legacy facts with the updated one.
=> (CAT-2205): Replaced legacy fact osfamily with os.family
