puppetlabs/puppetlabs-powershell

.gitignore, .project, .sync.yml, .travis.yml, CONTRIBUTING.md, Gemfile, appveyor.yml, lib/puppet/provider/exec/powershell.rb, spec/spec_helper.rb, spec/unit/provider/exec/powershell_spec.rb
This ensures the following items are under moduleysnc:
* .gitignore
* .travis.yml
* CONTRIBUTING.md
* Gemfile
* appveyor.yml
* spec/spec.opts
Most importantly, this ensures that acl has up to date Gemfile, Travis CI and
AppVeyor configurations that allow it to be tested properly.
=> (MODULES-2207) Update Modulesync

CHANGELOG.md, metadata.json
- Add metadata for PE 2015.2 and Puppet 4.0
=> (FM-3079) Release 1.0.5 - PE 2015.2.0 update

README.md
Not knowing/remembering this bit me badly (see ticket [MODULES-3007](https://tickets.puppetlabs.com/browse/MODULES-3007)). I hope this small addition to README.md helps other people to save time and debugging effort.
=> Mention that templates need to have DOS linefeeds

spec/acceptance/exec_powershell_spec.rb, spec/spec_helper.rb
Add acceptance tests for PowerShell single session support. Also, I found
some small typos that I fixed as well.
[skip-ci]
=> (MODULES-3011) Acceptance Test for Single Session

.sync.yml, CONTRIBUTING.md, Gemfile, LICENSE, MAINTAINERS.md, NOTICE, appveyor.yml
=> Merge stable to master

Gemfile
The PR contains the updates from the new modsync config for windows;
- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup
https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61
=> (maint) modsync update - master

CONTRIBUTING.md, README.md, metadata.json
Update all references from puppetlabs to puppet
=> (MODULES-3356) Branding Name Change

CHANGELOG.md
This commit updates the module in preparation for the 2.0.0 release.
=> (FM-4639) Prepare module for 2.0.0 release

spec/acceptance/exec_powershell_spec.rb
- These tests were initially validated against a local definition
that only included Windows agents.
However, in CI, there are masters that are configured as agents as
well, and some of these tests don't make sense.
Refactor all the tests to run manifests only on Windows agents.
=> (MODULES-2634) Fix tests for non-Windows agents

CHANGELOG.md, metadata.json
This commit prepares for the release of version 2.0.2 of the powershell module.
- Update CHANGELOG
- Update version in metadata
=> (FM-5344) Prepare for release 2.0.2

lib/puppet_x/puppetlabs/powershell/powershell_manager.rb, lib/puppet_x/templates/init_ps.ps1, lib/puppet_x/templates/init_ps.ps1.erb
- Pulls extraneous output from Invoke-PowerShellUserCode
- Refactors event signaling
=> (maint) Minor PS tweaks in prep for pipe rewrite

README.md
Added a thing about here-strings. Hit up a few editorial and formatting fixes while I was in there.
=> DOC-2960: new limitation and a bit of editing

CHANGELOG.md, metadata.json
Update changelog and metadata.json for release
=> (FM-5728) Update changelog for 2.1.0

CHANGELOG.md
Push changelog date so we could tie up some loose ends
=> (FM-5728) Update Changlog Date

metadata.json
MODULES-4822 puppetlabs-powershell: Update the version compatibility to >= 4.7.0 < 5.0.0
=> MODULES-4822 puppetlabs-powershell: Update the version compatibility to >= 4.7.0 < 5.0.0

lib/puppet_x/templates/init_ps.ps1, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- Previously the custom PSHost implementation (PuppetPSHost) was not
inspected for Output in the face of an error.
This is problematic as completely valid information may have been
written to stdout / stderr via the Write-Output / Write-Debug /
Write-Error cmdlets (or other mechanisms).  This output can be
helpful for end users to determine where executing PowerShell code
may have failed.
Add tests demonstrating such a trivial case, where the timeout for
the script is set to 1.5 seconds, but the script has a `sleep 10`
preventing it from completing successfully.
Previously, none of the output would be collected in this error
situation - but now the result object has more information
populated.
This should be very helpful for debugging.
- Though not strictly necessary, ask the PowerShell …
=> (MODULES-5145) Return available UI Output on error

lib/puppet_x/templates/powershell/init_ps.ps1
Reverts puppetlabs/puppetlabs-powershell#214
=> Revert "(IMAGES-795) 2008r2 template failing PowerShell module tests"

.sync.yml, Gemfile, spec/acceptance/exec_powershell_spec.rb, spec/spec_helper_acceptance.rb
This commit adds the testmode switcher gem and modifies the tests to use test
mode switcher.  This allows acceptance tests to run with or without a master.
=> (MODULES-6750) Add testmode switcher

metadata.json
This commit updates the CHANGELOG.md and METADATA.json files to prep for
the 2.1.4 release of the module.
=> (MODULES-6937) Release Prep 2.1.4

CHANGELOG.md
CHANGELOG edits to follow KAC format.
=> (MODULES-7109) CHANGELOG edits

CHANGELOG.md, metadata.json
=> Mergeback release into master

CHANGELOG.md, metadata.json
This commit updates the module in preparation for a v2.2.0 release
=> (MODULES-8120) Prepare module for 2.2.0 release

lib/puppet/provider/exec/powershell.rb
https://tickets.puppetlabs.com/browse/MODULES-7067
=> (MODULES-7067) Only initialise constant when not defined

spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/unit/provider/exec/powershell_spec.rb, spec/unit/provider/exec/pwsh_spec.rb, spec/unit/puppet_x/puppetlabs/powershell/compatible_powershell_version_spec.rb, spec/unit/puppet_x/puppetlabs/powershell/powershell_version_spec.rb
to facilitate more complete test output from our unit tests.
=> (WIN-280) add skip() unless pattern to tests

CHANGELOG.md, metadata.json
This commit updates the module for a version 2.3.0 release.
=> (MODULES-8924) Prepare module for 2.3.0 release

README.md
This commit makes minor edits, including formatting adjustments for consistency.
=> (MODULES-8924) DOCS Release Review

.sync.yml, Gemfile
Request for a review.
Add the dependent gems to system group in .sync.yml file and ran pdk update
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/modules/view/windows/view/_adhoc/view/powershell/
=> (maint) Adding gems

metadata.json
=> (MAINT) - update dependencies

CHANGELOG.md, metadata.json
=> (MODULES-10164) Release version v3.0.1

.sync.yml, .travis.yml, Rakefile, appveyor.yml, metadata.json, spec/spec_helper.rb
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
=> (IAC-365) updating tokens and dataset for honeycomb

.rubocop.yml, .sync.yml, .vscode/extensions.json, Gemfile, metadata.json, spec/spec_helper.rb
=> (maint) pin bolt to 2.6.0 version for work around of invalid exit code

CHANGELOG.md, metadata.json
=> (IAC-950) Release Merge Back v4.0.0

.sync.yml, .travis.yml, Rakefile, appveyor.yml, metadata.json
(IAC-973) - Update travis/appveyor to run on new default branch `main`
pdk version: `1.18.1`
=> pdksync - (IAC-973) - Update travis/appveyor to run on new default branch `main`

CHANGELOG.md, metadata.json
=> (MAINT) Prep for 4.1.0 release

metadata.json
Update gha templates
pdk version: `1.19.0.pre (47)`
=> pdksync - Update gha templates

.github/workflows/auto_release.yml, Gemfile, metadata.json, spec/spec_helper.rb
PDK Update for auto release prep workflow
pdk version: `1.18.1`
=> pdksync - PDK Update for auto release prep workflow

.devcontainer/README.md, .devcontainer/devcontainer.json, .github/workflows/auto_release.yml, .github/workflows/nightly.yml, .github/workflows/pr_test.yml, .github/workflows/spec.yml, .gitignore, .gitpod.yml, .pdkignore, .rubocop.yml, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
pdksync_heads/main-0-gf3911d3
pdk version: `2.3.0`
=> pdksync - pdksync_heads/main-0-gf3911d3
